### ISSUE TITLE
Routes are incorrectly read when h5py 2.6.0 is used

### ISSUE THREAD

**Issue by smaret** [smaret/astrochem#50]
Astrochem full test (`astrochem_test`) fails with the following message:

```
PASS: input_test
PASS: source_test
PASS: source_dyn_test
PASS: network_test
PASS: rate_test
PASS: abundances_test
PASS: solver_test
PASS: python_lib_test
PASS: python_tools_test
FAIL: astrochem_test
============================================================================
Testsuite summary for astrochem 0.7-beta
============================================================================
# TOTAL: 10
# PASS:  9
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0
```

From `tests/test-suite.log`:

```
FAIL: astrochem_test
====================

Reading input from ./input.ini.
Reading reactions network from /Users/smaret/Models/astrochem/networks/osu2009.chm... Found 6046 reactions involving 468 species.
Reading input from ./input.ini.
Reading source model from source.mdl.
Computing abundances in cell 0...
Done with cell 0.
F
======================================================================
FAIL: test_read_chm (__main__.TestSequenceFunctions)
----------------------------------------------------------------------

Traceback (most recent call last):
  File "./astrochem_test", line 118, in test_read_chm
    numpy.testing.assert_almost_equal( a.tolist(), a_o )
  File "/usr/local/lib/python2.7/site-packages/numpy/testing/utils.py", line 517, in assert_almost_equal
    return assert_array_almost_equal(actual, desired, decimal, err_msg)
  File "/usr/local/lib/python2.7/site-packages/numpy/testing/utils.py", line 912, in assert_array_almost_equal
    precision=decimal)
  File "/usr/local/lib/python2.7/site-packages/numpy/testing/utils.py", line 733, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Arrays are not almost equal to 7 decimals

(mismatch 98.2421875%)
```

**Comment by smaret** [comment]
The problem occurs when reading the formation/destruction routes in the HDF5 file:

```python
t,s,a,b,c,d = tools.readrout( filename , "H3O(+)" )
```

The `a` array should contain the formation reactions. For the first time step, this array gives:

```python
print(a[0, 0, :])
>>> [  171374182        1378   912232078  1457060642        2956   938978995
       2123506789        2944   902744583   342948541        1922   929061017
       1856279952        1378   917990950 -1831350047]
```

which is obviously incorrect.

**Comment by smaret** [comment]
The bug occurs with `h5py` 2.6.0, but it does not occur with previous version (2.5.0). This is most likely a bug in `h5py`, and not in `astrochem`. 

There are indeed several bug reports with this version (see h5py/h5py#742 for example).
